services:
  visacheckapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visacheckapp
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
